#!/bin/sh
        mount -t devtmpfs dev /dev
        mount -t proc proc /proc
        mount -t sysfs sysfs /sys
        ip link set up dev lo
        cd /app

        export MODE=server
export GRPC_PORT=8081

        ./hello-grpc

        exec /sbin/getty -n -l /bin/sh 115200 /dev/console
        poweroff -f
    