services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ROOTNAME
      MINIO_ROOT_PASSWORD: CHANGEME123
    volumes:
      - ./minio/data:/data
    command: server /data --console-address ":9001"
    networks:
      - sealci
  release-agent:
    build: .
    container_name: release-agent
    ports:
      - "50052:50052"
    networks:
      - sealci
    environment:
      CERT_PATH: /tmp
      GIT_PATH: /tmp
      BUCKET_ACCESS_KEY: ROOTNAME
      BUCKET_SECRET_KEY: CHANGEME123
      BUCKET_NAME: sealci
      BUCKET_ADDR: http://minio:9000
      GRPC: 0.0.0.0:50052
    

networks:
  sealci:
